### PR TITLE
Create node.js.yml

### PR DESCRIPTION
**Pull request by faizm10**

### CODE REVIEW

**Review by basilysf1709 — COMMENTED** [review]
What is this?

**Comment by basilysf1709** [comment]
> What is this?

Is this supposed to be a CI pipeline?
- Where's Lint check
- What is the thought process?

**Comment by basilysf1709** [comment]
@faizm10 You wrote `npm test`, I don't see a change in package.json to account for this change?

**Comment by faizm10** [comment]
> @faizm10 You wrote `npm test`, I don't see a change in package.json to account for this change?

bro idk what i am doing 💀 i am jus following youtube

**Comment by basilysf1709** [comment]
@faizm10 Debug pls! Your pipeline is failing

**Comment by basilysf1709** [comment]
> > @faizm10 You wrote `npm test`, I don't see a change in package.json to account for this change?
> 
> @basilysf1709 bro idk what i am doing 💀 i am jus following youtube

Fix the mistakes and make a PR again

**Pull request closed without merging**
